name: .NET

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'      
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore FuelCostCalculator/FuelCostCalculator.csproj

      - name: Build MAUI Windows
        run: msbuild FuelCostCalculator/FuelCostCalculator.csproj -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net8.0-windows10.0.19041 /p:GenerateAppxPackageOnBuild=true

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-ci-build
          path: FuelCostCalculator/bin/Release/net8.0-windows*/**/FuelCostCalculator*.msix

  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore FuelCostCalculator/FuelCostCalculator.csproj

      - name: Build MAUI Android
        run: dotnet build FuelCostCalculator/FuelCostCalculator.csproj -c Release -f net8.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: android-ci-build
          path: FuelCostCalculator/bin/Release/net8.0-android/*Signed.a*