name: FuelCostCalculator

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'      
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-2022
    name: Android Build & Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore FuelCostCalculator/FuelCostCalculator.csproj

      - name: Build MAUI Android
        run: dotnet build FuelCostCalculator/FuelCostCalculator.csproj -c Release -f net8.0-android --no-restore
      
      - name: Initialize Date-based Versioning
        id: set_version
        run: echo "::set-output name=version::$(date -u +%Y-%m-%d)"
      
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: android-ci-build
          path: FuelCostCalculator/bin/Release/net8.0-android/*.apk

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          files: |
            FuelCostCalculator/bin/Release/net8.0-android/*.apk
          tag_name: ${{ steps.set_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    runs-on: macos-11
    name: iOS Build & Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore FuelCostCalculator/FuelCostCalculator.csproj

      - name: Build MAUI iOS
        run: dotnet build FuelCostCalculator/FuelCostCalculator.csproj -f net8.0-ios -c Release --no-restore

      - name: Initialize Date-based Versioning
        id: set_version
        run: echo "::set-output name=version::$(date -u +%Y-%m-%d)"
      
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ios-ci-build
          path: FuelCostCalculator/bin/Release/net8.0-ios/*.ipa

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          files: |
            FuelCostCalculator/bin/Release/net8.0-ios/*.ipa
          tag_name: ${{ steps.set_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-2022
    name: Windows Build & Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore FuelCostCalculator/FuelCostCalculator.csproj

      - name: Build MAUI Windows
        run: dotnet build FuelCostCalculator/FuelCostCalculator.csproj -c Release -f net8.0-windows --no-restore

      - name: Initialize Date-based Versioning
        id: set_version
        run: echo "::set-output name=version::$(date -u +%Y-%m-%d)"
      
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows-ci-build
          path: FuelCostCalculator/bin/Release/net8.0-windows/*.exe

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          files: |
            FuelCostCalculator/bin/Release/net8.0-windows/*.exe
          tag_name: ${{ steps.set_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}